#!/usr/bin/env python3
"""Build RiftFlythrough texture_map.js from flythrough-index.json.

Reads linked_textures from flythrough-index.json and generates a TEXTURE_MAP
JavaScript constant mapping NIF asset IDs to converted PNG texture paths.

Output: C:/RIFT MODDING/RiftFlythrough/js/texture_map.js

Usage:
    python scripts/build_texture_map.py                    # generate texture_map.js
    python scripts/build_texture_map.py --dry-run          # preview without writing
    python scripts/build_texture_map.py --copy-textures     # also copy PNGs to RiftFlythrough
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

ASSETS_REPO = Path(__file__).resolve().parents[1]
INDEX_PATH = ASSETS_REPO / "Assets" / "build" / "flythrough" / "flythrough-index.json"
CONVERTED_DIR = ASSETS_REPO / "Assets" / "build" / "flythrough" / "textures" / "converted"
RIFTFLYTHROUGH = ASSETS_REPO.parent / "RiftFlythrough"
TEXTURE_MAP_JS = RIFTFLYTHROUGH / "js" / "texture_map.js"
RFT_TEXTURES_DIR = RIFTFLYTHROUGH / "textures" / "converted"

# Relative path from RiftFlythrough/ to Assets/build/flythrough/textures/converted/
# RiftFlythrough -> ../Assets/Assets/build/flythrough/textures/converted/
RELATIVE_TEXTURE_PATH = "../Assets/Assets/build/flythrough/textures/converted"


def generate_texture_map_js(
    index: dict,
    *,
    relative_base: str = RELATIVE_TEXTURE_PATH,
) -> str:
    """Generate texture_map.js content from flythrough-index.json assets."""
    assets: dict = index.get("assets", {})

    entries: list[tuple[str, str]] = []  # (pattern, url)
    seen: set[tuple[str, str]] = set()

    for asset_id, asset in sorted(assets.items()):
        linked = asset.get("linked_textures", [])
        if not linked:
            continue
        for png_name in linked:
            edge = (asset_id, png_name)
            if edge not in seen:
                seen.add(edge)
                url = f"{relative_base}/{png_name}"
                entries.append((asset_id, url))

    if not entries:
        return _generate_empty_map()

    lines = [
        "// Auto-generated by build_texture_map.py — NIF hash to PNG texture mapping.",
        f"// Source: {INDEX_PATH.name}",
        f"// Textures: {len(entries)} entries across {len({e[0] for e in entries})} assets",
        "const TEXTURE_MAP = [",
    ]

    for pattern, url in entries:
        # Escape backslashes for JS string (though URLs use forward slashes)
        url_escaped = url.replace("\\", "/")
        lines.append(f'  {{ pattern: "{pattern}", url: "{url_escaped}" }},')

    lines.append("];")
    return "\n".join(lines) + "\n"


def _generate_empty_map() -> str:
    """Generate a minimal texture_map.js with no entries."""
    return (
        "// Auto-generated by build_texture_map.py — NIF hash to PNG texture mapping.\n"
        "// No linked textures found in flythrough-index.json.\n"
        "const TEXTURE_MAP = [];\n"
    )


def copy_textures_to_riftflythrough(
    index: dict,
    *,
    dry_run: bool = False,
) -> dict:
    """Copy linked PNG textures from Assets repo to RiftFlythrough textures/converted/.

    Returns stats dict with copied, skipped, missing counts and dry_run flag."""
    assets: dict = index.get("assets", {})
    rft_textures_dir = RFT_TEXTURES_DIR

    stats: dict[str, int | bool] = {"copied": 0, "skipped": 0, "missing": 0, "dry_run": dry_run}
    seen_pngs: set[str] = set()

    for asset in assets.values():
        for png_name in asset.get("linked_textures", []):
            if png_name in seen_pngs:
                continue
            seen_pngs.add(png_name)

            src = CONVERTED_DIR / png_name
            dst = rft_textures_dir / png_name

            if not src.exists():
                stats["missing"] += 1
                print(f"  MISSING: {png_name}", file=sys.stderr)
                continue

            if dst.exists() and dst.stat().st_size == src.stat().st_size:
                stats["skipped"] += 1
                continue

            if not dry_run:
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
            stats["copied"] += 1

    return stats


def main() -> int:
    parser = argparse.ArgumentParser(description="Build texture_map.js for RiftFlythrough")
    parser.add_argument("--dry-run", action="store_true", help="Preview output without writing")
    parser.add_argument("--copy-textures", action="store_true", help="Also copy PNG files to RiftFlythrough")
    args = parser.parse_args()

    if not INDEX_PATH.exists():
        print(f"ERROR: {INDEX_PATH} not found. Run the FT pipeline first.", file=sys.stderr)
        return 1

    if not args.dry_run and not RIFTFLYTHROUGH.exists():
        print(f"ERROR: RiftFlythrough not found at {RIFTFLYTHROUGH}", file=sys.stderr)
        return 1

    with open(INDEX_PATH, encoding="utf-8-sig") as f:
        index = json.load(f)

    js_content = generate_texture_map_js(index)

    if args.dry_run:
        # Show first 15 lines and stats
        lines = js_content.split("\n")
        print("\n".join(lines[:15]))
        entry_count = js_content.count("pattern:")
        print(f"\n... ({entry_count} total entries, {len(lines)} lines)")
        print(f"[DRY-RUN] Would write to: {TEXTURE_MAP_JS}")
    else:
        TEXTURE_MAP_JS.parent.mkdir(parents=True, exist_ok=True)
        tmp = str(TEXTURE_MAP_JS) + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(js_content)
        os.replace(tmp, str(TEXTURE_MAP_JS))

        entry_count = js_content.count("pattern:")
        asset_count = len({line.split('"')[1] for line in js_content.split("\n") if "pattern:" in line})
        print(f"Generated texture_map.js: {entry_count} entries, {asset_count} assets")
        print(f"Written: {TEXTURE_MAP_JS}")

    if args.copy_textures:
        if args.dry_run:
            print("\n[DRY-RUN] Would copy textures to RiftFlythrough...")
        else:
            print("\nCopying textures to RiftFlythrough...")
        stats = copy_textures_to_riftflythrough(index, dry_run=args.dry_run)
        verb = "would copy" if stats["dry_run"] else "copied"
        print(f"Textures: {stats['copied']} {verb}, {stats['skipped']} skipped, {stats['missing']} missing")

    return 0


if __name__ == "__main__":
    sys.exit(main())
