"""navmesh_debug_export.py — Shared debug OBJ export utilities for navmesh visualization.

Provides functions to export:
  - Recast navmesh polygons as color-coded OBJ faces
  - Detour path waypoints as line segments with start/goal markers

All exports use Wavefront OBJ with `usemtl` tags for color-coding in
RiftFlythrough or other OBJ viewers.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import TextIO

# Material names used for color-coding in OBJ viewers.
MAT_NAVMESH_WALKABLE = "navmesh_walkable"
MAT_NAVMESH_EDGE = "navmesh_edge"
MAT_PATH_ROUTE = "path_route"
MAT_PATH_START = "path_start"
MAT_PATH_GOAL = "path_goal"

# Default material colors (RGB, 0-1).
_MATERIALS: dict[str, tuple[float, float, float]] = {
    MAT_NAVMESH_WALKABLE: (0.0, 0.8, 0.0),  # green
    MAT_NAVMESH_EDGE: (0.0, 0.4, 0.0),  # dark green
    MAT_PATH_ROUTE: (1.0, 0.0, 0.0),  # red
    MAT_PATH_START: (0.0, 1.0, 0.0),  # bright green
    MAT_PATH_GOAL: (0.0, 0.0, 1.0),  # blue
}


def _write_obj_header(f: TextIO, title: str, *, mtl_name: str | None = None) -> None:
    """Write a standard OBJ header comment and optional mtllib reference."""
    f.write(f"# {title}\n")
    if mtl_name:
        f.write(f"mtllib {mtl_name}\n")


def write_mtl_file(out_path: Path) -> None:
    """Write a minimal MTL file with color definitions for navmesh/path materials.

    Args:
        out_path: Destination MTL path.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Navmesh/path debug materials\n")
        for name, (r, g, b) in _MATERIALS.items():
            f.write(f"newmtl {name}\n")
            f.write(f"Kd {r:.4f} {g:.4f} {b:.4f}\n")
            f.write("Ka 0.2 0.2 0.2\n")
            f.write("Ks 0.0 0.0 0.0\n")
            f.write("Ns 0.0\n\n")


def _compute_marker_size(
    vertices: list[list[float] | tuple[float, float, float]],
    waypoints: list[tuple[float, float, float]] | None = None,
    fallback: float = 1.0,
) -> float:
    """Compute a reasonable marker size from the bounding box of the scene.

    Marker size is 2% of the largest bounding-box extent, clamped to
    [0.1, 50.0] world units.
    """
    points: list[list[float] | tuple[float, float, float]] = list(vertices)
    if waypoints:
        points.extend(waypoints)
    if not points:
        return fallback

    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    zs = [p[2] for p in points]
    extent = max(
        max(xs) - min(xs),
        max(ys) - min(ys),
        max(zs) - min(zs),
    )
    return max(0.1, min(50.0, extent * 0.02))


def _fan_triangulate(poly: list[int]) -> list[tuple[int, int, int]]:
    """Fan-triangulate a convex polygon into 1-indexed OBJ face triples."""
    if len(poly) < 3:
        return []
    return [(poly[0] + 1, poly[j] + 1, poly[j + 1] + 1) for j in range(1, len(poly) - 1)]


def export_navmesh_to_obj(
    vertices: list[list[float] | tuple[float, float, float]],
    polys: list[list[int]],
    out_path: Path,
    *,
    include_edges: bool = True,
    name: str = "navmesh",
) -> None:
    """Export navmesh polygons as a debug OBJ.

    Args:
        vertices: List of [x, y, z] vertices.
        polys: List of polygons, each a list of 0-indexed vertex indices.
        out_path: Destination OBJ path.
        include_edges: If True, also emit boundary edges as line segments.
        name: Object name to use in the OBJ file.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    mtl_name = out_path.with_suffix(".mtl").name
    write_mtl_file(out_path.with_suffix(".mtl"))

    with open(out_path, "w", encoding="utf-8") as f:
        _write_obj_header(f, "Navmesh debug OBJ — generated by navmesh_debug_export.py", mtl_name=mtl_name)
        f.write(f"# Polymesh: {len(polys)} polys, {len(vertices)} verts\n")

        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        f.write(f"o {name}\nusemtl " + MAT_NAVMESH_WALKABLE + "\n")
        for poly in polys:
            for i0, i1, i2 in _fan_triangulate(poly):
                f.write(f"f {i0} {i1} {i2}\n")

        if include_edges:
            f.write("usemtl " + MAT_NAVMESH_EDGE + "\n")
            for poly in polys:
                if len(poly) < 2:
                    continue
                for j in range(len(poly)):
                    a = poly[j] + 1
                    b = poly[(j + 1) % len(poly)] + 1
                    f.write(f"l {a} {b}\n")


def _add_marker(
    f: TextIO,
    center: tuple[float, float, float],
    size: float,
    material: str,
    base_index: int,
) -> int:
    """Write a small octahedral marker centered on ``center``.

    Returns the number of new vertices written (6 for an octahedron).
    The octahedron is symmetric around ``center`` so it sits on the point
    rather than sinking below it.
    """
    cx, cy, cz = center
    verts = [
        (cx + size, cy, cz),  # +x
        (cx - size, cy, cz),  # -x
        (cx, cy + size, cz),  # +y (top)
        (cx, cy - size, cz),  # -y (bottom)
        (cx, cy, cz + size),  # +z
        (cx, cy, cz - size),  # -z
    ]
    for v in verts:
        f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

    f.write(f"usemtl {material}\n")
    # Octahedron faces (1-indexed relative to base_index)
    faces = [
        # Top half (around +y vertex)
        (base_index + 3, base_index + 1, base_index + 5),
        (base_index + 3, base_index + 5, base_index + 2),
        (base_index + 3, base_index + 2, base_index + 6),
        (base_index + 3, base_index + 6, base_index + 1),
        # Bottom half (around -y vertex)
        (base_index + 4, base_index + 5, base_index + 1),
        (base_index + 4, base_index + 2, base_index + 5),
        (base_index + 4, base_index + 6, base_index + 2),
        (base_index + 4, base_index + 1, base_index + 6),
    ]
    for i0, i1, i2 in faces:
        f.write(f"f {i0} {i1} {i2}\n")
    return len(verts)


def export_path_to_obj(
    waypoints: list[tuple[float, float, float]],
    out_path: Path,
    *,
    marker_size: float | None = None,
    name: str = "path",
) -> None:
    """Export a path as a debug OBJ with line segments and start/goal markers.

    Args:
        waypoints: List of (x, y, z) path waypoints in world coordinates.
        out_path: Destination OBJ path.
        marker_size: Size of the start/goal marker geometry. If None, auto-scaled.
        name: Object name prefix to use in the OBJ file.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    mtl_name = out_path.with_suffix(".mtl").name
    write_mtl_file(out_path.with_suffix(".mtl"))

    if marker_size is None:
        marker_size = _compute_marker_size([], waypoints)

    with open(out_path, "w", encoding="utf-8") as f:
        _write_obj_header(f, "Path debug OBJ — generated by navmesh_debug_export.py", mtl_name=mtl_name)
        f.write(f"# Waypoints: {len(waypoints)}\n")

        # Write all waypoints as vertices
        for wp in waypoints:
            f.write(f"v {wp[0]:.6f} {wp[1]:.6f} {wp[2]:.6f}\n")

        # Path line segments
        if len(waypoints) >= 2:
            f.write(f"o {name}_route\nusemtl " + MAT_PATH_ROUTE + "\n")
            for i in range(len(waypoints) - 1):
                f.write(f"l {i + 1} {i + 2}\n")

        # Start and goal markers
        if waypoints:
            start = waypoints[0]
            goal = waypoints[-1]
            vertex_count = len(waypoints)

            f.write(f"o {name}_start\n")
            vertex_count += _add_marker(f, start, marker_size, MAT_PATH_START, vertex_count)

            f.write(f"o {name}_goal\n")
            _add_marker(f, goal, marker_size, MAT_PATH_GOAL, vertex_count)


def export_navmesh_and_path(
    navmesh_result: dict,
    waypoints: Iterable[tuple[float, float, float]] | None,
    out_path: Path,
    *,
    include_edges: bool = True,
    marker_size: float | None = None,
    name: str = "navmesh",
) -> None:
    """Export both a navmesh and an optional path into a single debug OBJ.

    Args:
        navmesh_result: Dict with 'verts' and 'polys' keys (from build_navmesh).
        waypoints: Optional list of path waypoints.
        out_path: Destination OBJ path.
        include_edges: Include navmesh boundary edges.
        marker_size: Size of start/goal markers. If None, auto-scaled.
        name: Object name prefix to use in the OBJ file.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    mtl_name = out_path.with_suffix(".mtl").name
    write_mtl_file(out_path.with_suffix(".mtl"))

    vertices = navmesh_result.get("verts", [])
    polys = navmesh_result.get("polys", [])

    if marker_size is None:
        marker_size = _compute_marker_size(vertices, list(waypoints) if waypoints else None)

    with open(out_path, "w", encoding="utf-8") as f:
        _write_obj_header(f, "Navmesh + path debug OBJ — generated by navmesh_debug_export.py", mtl_name=mtl_name)
        f.write(f"# Navmesh: {len(polys)} polys, {len(vertices)} verts\n")

        # Write navmesh vertices first
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        # Write path waypoints as additional vertices
        path_points: list[tuple[float, float, float]] = list(waypoints) if waypoints else []
        if path_points:
            f.write(f"# Path waypoints: {len(path_points)}\n")
            for wp in path_points:
                f.write(f"v {wp[0]:.6f} {wp[1]:.6f} {wp[2]:.6f}\n")

        # Navmesh faces
        f.write(f"o {name}\nusemtl " + MAT_NAVMESH_WALKABLE + "\n")
        for poly in polys:
            for i0, i1, i2 in _fan_triangulate(poly):
                f.write(f"f {i0} {i1} {i2}\n")

        # Navmesh edges
        if include_edges:
            f.write("usemtl " + MAT_NAVMESH_EDGE + "\n")
            for poly in polys:
                if len(poly) < 2:
                    continue
                for j in range(len(poly)):
                    a = poly[j] + 1
                    b = poly[(j + 1) % len(poly)] + 1
                    f.write(f"l {a} {b}\n")

        # Path line segments (indices offset by navmesh vertex count)
        if path_points:
            offset = len(vertices)
            f.write(f"o {name}_route\nusemtl " + MAT_PATH_ROUTE + "\n")
            for i in range(len(path_points) - 1):
                f.write(f"l {offset + i + 1} {offset + i + 2}\n")

            # Start/goal markers
            start = path_points[0]
            goal = path_points[-1]
            base_index = offset + len(path_points)

            f.write(f"o {name}_start\n")
            base_index += _add_marker(f, start, marker_size, MAT_PATH_START, base_index)

            f.write(f"o {name}_goal\n")
            _add_marker(f, goal, marker_size, MAT_PATH_GOAL, base_index)
